site_name: MW Tutorials
site_url: http://www.example.com

nav:
  - Home: index.md
  - Events: topics/events.md
  - Mitmachen:
    - Unsere Chorgruppen: chorgruppen.md
    - Fördermöglichkeiten: foerderung.md
  - Fotos: topics/fotos.md
  - Verein:
    - Künstlerische Leitung: leitung.md
    - Kontakt: kontakt.md
    - Dokumente: dokumente.md
  - Shop: shop.md
  - Übersetzung: translation.md

theme: 
  name: readthedocs
  logo: docs/img/Logo_Signet_Quadrat.jpg
  locale: de

