site_name: MW Tutorials
site_url: http://www.example.com

nav:
  - Home: index.md
  - Verein:
    - Künstlerische Leitung: leitung.md
    - Kontakt: kontakt.md
    - Dokumente: dokumente.md
  - Mitmachen:
    - Unsere Chorgruppen: chorgruppen.md
    - Fördermöglichkeiten: foerderung.md
  - Events: topics/events/events.md
  - Fotos: 
    - Fotos: topics/fotos/fotos.md
    - Galerie erstellen: topics/fotos/galerie_erstellen.md
    - Galerie kopieren: topics/fotos/galerie_kopieren.md
    - Galerie konfigurieren: topics/fotos/galerie_konfigurieren.md
    - Bilder hinzufügen: topics/fotos/bilder_hinzufugen.md
    - Galerie veröffentlichen: topics/fotos/galerie_veroffentlichen.md
    - Fotoseite anlegen: topics/fotos/fotoseite_anlegen.md
    - Fotoseite anordnen: topics/fotos/fotoseite_anordnen.md
    - Hauptseite anpassen: topics/fotos/hauptseite_anpassen.md
  - Shop: shop.md
  - Übersetzung: translation.md

theme: 
  name: readthedocs
  logo: docs/img/Logo_Signet_Quadrat.jpg
  locale: de

