site_name: MW Tutorials
site_url: http://www.example.com

nav:
  - Home: index.md
  - Verein:
    - Künstlerische Leitung: leitung.md
    - Kontakt: kontakt.md
    - Dokumente: dokumente.md
  - Mitmachen:
    - Unsere Chorgruppen: chorgruppen.md
    - Fördermöglichkeiten: foerderung.md
  - Events: events.md
  - Fotos: fotos.md
  - Shop: shop.md
